#logging:
#  level:
#    org.springframework: DEBUG
spring:
  config:
    activate:
      on-profile: local

  # H2 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource2:
    url: jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;DefaultDataset=TA_DATASET
    username: your-service-account-email
    password: your-service-account-password

springdoc:
  packages-to-scan: com.example.tlo.api
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  title: TLO Sample local api swagger
  version: v1.0.0
  description: LAMO :)
  cache:
    disabled: true
  swagger-ui:
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    path: /api-docs
    csrf:
      enabled: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  servers:
    - url: http://localhost:8080/tlo/api
      description: Localhost Server

logger:
  tlo:
    enable: true
    service-name: tlo-sample-was
    instance-name: tlo-sample
    instance-code: '999'
    base-dir: ./logs/tlo
    interval-minutes: 5
    check-interval-millis: 1000
    use-immediately-write: false

